MIN_RESPONSE_TIME = 2.0
MAX_RESPONSE_TIME = 120.0

MIN_HESITATION = 0.0
MAX_HESITATION = 30.0

MAX_ANSWER_CHANGES = 4

DEFAULT_SESSION_BREAK_MINUTES = 15

MIN_SESSION_DURATION = 5
MAX_SESSION_DURATION = 180